services:
  way-finding:
    image: ghcr.io/m6o4/way-finding:latest
    container_name: way-finding
    restart: unless-stopped
    networks:
      - m6o4-prd-network
    env_file:
      - stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.way-finding.rule=Host(`way-finding.co.ke`) ||
        Host(`www.way-finding.co.ke`)"
      - "traefik.http.routers.way-finding.entrypoints=websecure"
      - "traefik.http.routers.way-finding.tls.certresolver=letsencrypt"
      - "traefik.http.services.way-finding.loadbalancer.server.port=3000"

networks:
  m6o4-prd-network:
    external: true
    name: m6o4-prd-network
